name = "medhashi-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "medhashi-db"
database_id = "4e4e9d6e-827d-4ff2-83f1-ec786c44ed01"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "medhashi-media"

[vars]
ENVIRONMENT = "production"
